version: '3.8'
# Disco-Machina - AI-powered Development Team Terminal Client
# Created by Yavuz Topsever (https://github.com/yavuztopsever)

services:
  disco-machina-api:
    build: .
    image: disco-machina:latest
    container_name: disco-machina-api
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BRAVE_API_KEY=${BRAVE_API_KEY:-}
      - GH_TOKEN=${GH_TOKEN:-}
    env_file:
      - .env
    command: server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # To run as a CLI instead of server, you can use:
  # 
  # dev-team-cli:
  #   build: .
  #   image: dev-team:latest
  #   container_name: dev-team-cli
  #   volumes:
  #     - ./output:/app/output
  #   environment:
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - BRAVE_API_KEY=${BRAVE_API_KEY:-}
  #     - GH_TOKEN=${GH_TOKEN:-}
  #   env_file:
  #     - .env
  #   command: run "Your project goal" "/app/output/your-project"