requirements_analysis:
  description: "Analyze project requirements and create product backlog with user stories and acceptance criteria"
  agent: "project_manager"
  dependencies: []

architecture_design:
  description: "Design system components, organization, and data flow based on requirements"
  agent: "software_architect"
  dependencies: ["requirements_analysis"]

codebase_analysis:
  description: "Analyze existing code structure and identify improvements"
  agent: "software_architect"
  dependencies: ["architecture_design"]

sprint_planning:
  description: "Create sprint plan with prioritized backlog items"
  agent: "project_manager"
  dependencies: ["requirements_analysis", "codebase_analysis"]

feature_implementation:
  description: "Implement features according to sprint plan"
  agent: "fullstack_developer"
  dependencies: ["sprint_planning"]

test_development:
  description: "Write tests for implemented features"
  agent: "test_engineer"
  dependencies: ["feature_implementation"]

code_review:
  description: "Review code against quality standards"
  agent: "test_engineer"
  dependencies: ["feature_implementation", "test_development"]

code_refactoring:
  description: "Improve code structure and reduce complexity"
  agent: "software_architect"
  dependencies: ["code_review"]

code_cleanup:
  description: "Remove obsolete code and dependencies"
  agent: "software_architect"
  dependencies: ["code_refactoring"]

documentation_update:
  description: "Update documentation to reflect changes"
  agent: "project_manager"
  dependencies: ["code_cleanup"]

sprint_retrospective:
  description: "Analyze sprint outcomes and plan improvements"
  agent: "project_manager"
  dependencies: ["documentation_update"]